name: Continuous Deployment

on:
  push:
    branches:
      - "main"

jobs:
  continuous-deployment:
    if: "(!contains(github.event.head_commit.message, 'pipeline skip') && !contains(github.event.head_commit.message, 'skip pipeline')) || (!contains(github.event.head_commit.message, 'cd skip') && !contains(github.event.head_commit.message, 'skip cd'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: build container
        run: sam build --use-container
      - name: deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name contact-api --s3-bucket ${{ secrets.S3_BUCKET }} --s3-prefix ${{ secrets.S3_PREFIX }} --capabilities CAPABILITY_IAM --region ca-central-1
